# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: python -m pip install --upgrade pytest pytest-azurepipelines tox pytest-cov
  displayName: 'Install test frameworks'

- script: tox -e py
  displayName: 'Run Tox'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'